---
title: "GLM"
output: html_document
date: "2022-10-25"
---

```{r}
library(tidyverse)
```

The dataset is known to you from the lectures. It was collected by the Philippine Statistics Authority 2015 and contains data on family income and expenditure.
Our data is a subset of 15,000 of the 40,000 observations, focusing on four regions: Central Luzon, Ilocos, Davao, and Visayas. The original dataset can be accessed at  https://www.kaggle.com/grosvenpaul/family-income-and-expenditure

```{r setup, include=FALSE}
data <- read.csv("philippines_households.csv")

# For our purposes, we only need 3 columns
data <- data %>%
	select(Household.Head.Age, Total.Number.of.Family.members, Region)

glimpse(data)
```

```{r}
# Visualize the data
data %>%
	ggplot(aes(x = Household.Head.Age, y = Total.Number.of.Family.members, col = Region)) +
	geom_jitter(size = 1) +
	theme_minimal()
```
```{r}
# Assess the applicability of Poisson regression.
# Slice the data at each age-group and observe the distribution of the count response
bin_size <- 10

data %>%
	mutate(bins = round(Household.Head.Age / bin_size) * bin_size) %>%
	filter(bins > 10) %>%
	ggplot(aes(x = Total.Number.of.Family.members)) +
	geom_histogram() +
	facet_grid(cols = vars(bins)) +
	ggtitle("Household size distribution per age group")

```

```{r}
# First, use a simple Linear Regression to predict the family size
linreg <- lm(Total.Number.of.Family.members ~ poly(Household.Head.Age, 2), data = data)
summary(linreg)

preds <- predict(linreg, data)

# Plot the linear regression fit
data %>%
	mutate(preds = preds) %>%
	ggplot(aes(x = Household.Head.Age, y = Total.Number.of.Family.members)) +
	geom_jitter(size = 1) +
	geom_point(aes(x = Household.Head.Age, y = preds, col = 'blue')) +
	# geom_smooth(method = "lm") +
	theme_minimal()

# How was the regression successful in fitting the data?
# How would you improve the fit? Execute your idea and check the result both graphically and numerically
```

```{r}
# Let's try the Poisson regression, which should be better suited - we have count data
# and its distribution seem to be Poisson.
poiss_reg <- glm(Total.Number.of.Family.members ~ Household.Head.Age, family = 'poisson', data = data)
summary(poiss_reg)

# Get the Poisson regression predictions.
# preds <- predict(poiss_reg, data)
# Recall, how to change the linear regression output to the actual response
# preds <- exp(preds)
preds <- predict(poiss_reg, data, type = "response")

# Use the predictions to plot the Poisson regression fit
data %>%
	mutate(preds = preds) %>%
	ggplot(aes(x = Household.Head.Age, y = Total.Number.of.Family.members)) +
	geom_jitter(size = 1) +
	# ggplot can do glm by itself
	geom_smooth(method = 'glm', method.args = list(family = "poisson")) +
	geom_point(aes(x = Household.Head.Age, y = preds, col = "blue")) +
	theme_minimal()

# Questions> Look at the summary - what is the equation of the model?
#     Knowing the model prescription, think of how can we interpret the coefficients
#       Ask the usual question "How does the output change with a unit increase of the predictor?"
#       The relationship is multiplicative.
#       head_age + 1 -> fs = fs_prev * e^(coef)
```


```{r}
# But how do we compare the performance of the simple and Poisson regression?
# There is no F-score and R2 in the summary of Poisson model. We need to find a common ground!

# Solution: fit the linear regression again, but this time with the glm() function
# Find out how to do so - help(family) might help
linreg_glm <- glm(Total.Number.of.Family.members ~ Household.Head.Age, family = "gaussian", data = data)
# Compare the coefficients with the lm() output
summary(linreg_glm)

# Now we can compare the Poisson and Linear regressions. Lower AIC is better.
poiss_reg$aic
linreg_glm$aic

# Note: The models can't be compared through anova() either since they are not nested
```

```{r}
# Look at the data and the first Poisson regression fit.
# Do you think the fit needs more flexibility? If yes, change the model and verify it improved the fit
poiss_reg2 <- glm(Total.Number.of.Family.members ~ poly(Household.Head.Age, 2), family = 'poisson', data = data)

# Make predictions. Care for the correct transformation the outputs
preds2 <- predict(poiss_reg2, data)
# preds2 <- predict(poiss_reg2, data2, type = "response")
preds2 <- exp(preds2)

# Use the predictions to plot the Poisson regression fit
data %>%
	mutate(preds = preds2) %>%
	ggplot(aes(x = Household.Head.Age, y = Total.Number.of.Family.members)) +
	geom_jitter(size = 1) +
	geom_point(aes(x = Household.Head.Age, y = preds, col = "red")) +
	theme_minimal()

# Compare with the simple Poisson
poiss_reg2$aic
poiss_reg$aic

# Compare with the polynomial regression model
linreg_glm$aic
```
